on:
  push:
    branches:
    - master

name: example workflow to run tests
jobs:
  example_job:
    runs-on: ubuntu
    steps:
      - name: my first step
        run: python -m unittest file_with_tests.py
        shell: bash
  
